### ISSUE TITLE
Cannot create wallet through the api

### ISSUE THREAD

**Issue by dtigran** [blockchain/api-v1-client-php#73]
I'm trying to create Blockchain wallets using your service "service-my-wallet-v3" and "api-v1-client-php".
It worked 2 weeks ago, but now I can't create new wallet.  I have updated version to v0.26.1 

It shows me the error: 
1527572801668 - warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true
1527572801673 - error: undefined Error: address import format not supported
    at Function.Address.import (/usr/local/node/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/address.js:199:13)
    at createLegacyAddress (/usr/local/node/lib/node_modules/blockchain-wallet-service/src/create.js:78:35)
    at newWallet (/usr/local/node/lib/node_modules/blockchain-wallet-service/src/create.js:87:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

and returns an empty wallet response: 
object(Blockchain\Create\WalletResponse)[237]
  public 'guid' => null
  public 'address' => null
  public 'label' => null

Thanks in advance.

**Comment by dtigran** [comment]
I have find the problem. It occured when I try to create account with function **createWithKey**. 
Actually I don't imagine what is private-key for wallet and what the problem? 
Can anyone help me.
