### ISSUE TITLE
Unable to decode JSON response from Blockchain

### ISSUE THREAD

**Issue by mbsmt** [blockchain/api-v1-client-php#84]
I have installed Blockchain local machine and got the appropriate api key too. While using the code below, I am getting errors:
**Code:**
```
// Include the autoload.php from its vendor directory
require 'vendor/autoload.php';

// Create the base Blockchain class instance
$Blockchain = new \Blockchain\Blockchain('my_api_key');

// Needed before calling $Blockchain->Wallet or $Blockchain->Create
$Blockchain->setServiceUrl('http://localhost:3030/');

$wallet = $Blockchain->Create->create('1234', $email=null, $label=null);
print_r($wallet);
```

**Errors:**
```
> Fatal error: Uncaught Blockchain\Exception\Error: Unable to decode JSON response from Blockchain: in /var/www/html/vendor/blockchain/blockchain/src/Blockchain.php:157 Stack trace: #0 /var/www/html/vendor/blockchain/blockchain/src/Blockchain.php(113): Blockchain\Blockchain->_call() #1 /var/www/html/vendor/blockchain/blockchain/src/Create/Create.php(39): Blockchain\Blockchain->post('api/v2/create_w...', Array) #2 /var/www/html/vendor/blockchain/blockchain/src/Create/Create.php(14): Blockchain\Create\Create->doCreate('1234', NULL, NULL, NULL) #3 /var/www/html/index.php(11): Blockchain\Create\Create->create('1234', NULL, NULL) #4 {main} thrown in /var/www/html/vendor/blockchain/blockchain/src/Blockchain.php on line 157
```
May you help me to solve this issue please?

**Comment by Eloy-Gonzalez** [comment]
Yes i have the same problem, i running with server nginx and i check log and response with error 504 Time out 

2019/10/24 16:14:56 [error] 28407#28407: *46 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: dutibits.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock", host: "dutibits.com", referrer: "http://dutibits.com/"

**Comment by orgkid** [comment]
am Also experiencing this now  
``atal error:  Uncaught Blockchain\Exception\Error: Unable to decode JSON response from Blockchain: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>`atal error:  Uncaught Blockchain\Exception\Error: Unable to decode JSON response from Blockchain: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>`

when trying to create wallet
